---
cellIdPreamble: ""
datapoint: "last"

cells:
  node_exporter:
    dataRef: "node_exporter"
    
    strokeColor:
      dataRef: "node_exporter"
      thresholds:
        - { color: "green", level: 1 }      # borde verde si activo
        - { color: "red", level: 0 }        # borde rojo si caído
      gradientMode: "none"
      elementFilter:
        - { name: "path", position: "2", filter: 'stroke="#b09500"' }

    label:
      separator: "replace"
