---

cellIdPreamble: "cell-"
gradientMode: "hue"

cells:
  servidor_estado:
    dataRef: "up"
    label:
      separator: "replace"
      units: ""
    labelColor:
      thresholds:
        - { color: "red", level: 0 }     # Si la métrica vale 0 → rojo
        - { color: "green", level: 1 }   # Si la métrica vale 1 → verde
