---
cellIdPreamble: "cell-"
gradientMode: "none"
datapoint: "last"

cells:
  localhost_9100:
    dataRef: "up_localhost_9100"
    fillColor:
      dataRef: "up_localhost_9100"
      thresholds:
        - { color: "green", level: 0.5 }   # cualquier cosa ≥ 0.5 será verde
        - { color: "red", level: 0 }       # < 0.5 será rojo
      gradientMode: "none"
      elementFilter:
        - { name: "rect", position: ".*" }
        - { name: "path", position: ".*" }
    label:
      separator: "replace"

