---
cellIdPreamble: ""
datapoint: "last"

cells:
  SW-PEXT-SF1345-10:
    dataRef: "RT-VOIP-SF1345-01-172.29.198.10"
    
    strokeColor:
      dataRef: "RT-VOIP-SF1345-01-172.29.198.10"
      thresholds:
        - { color: "green", level: 1 }      # borde verde si activo
        - { color: "red", level: 0 }        # borde rojo si caído
      gradientMode: "none"
      elementFilter:
        - { name: "path"}

    label:
      separator: "replace"
