---
cellIdPreamble: "cell-"
gradientMode: "none"
datapoint: "last"

cells:
  localhost_9100:
    dataRef: "up_localhost_9100"
    fillColor:
      dataRef: "up_localhost_9100"
      thresholds:
        - { color: "red",   level: 0 }
        - { color: "green",   level: 1 }
        - { color: "yellow",   level: 2 }        
      gradientMode: "none"
      elementFilter:
        - { name: "rect", position: ".*" }
        - { name: "path", position: ".*" }
    label:
      separator: "replace"


