---

cellIdPreamble: "cell-"
gradientMode: "hue"

cells:
  "localhost:9100":
    dataRef: "up"
    fillColor:
      dataRef: "up"
      thresholds:
        - {color: "green", level: 1}
        - {color: "red",   level: 0}
      gradientMode: "none"
      elementFilter:
        - {name: "rect", position: ".*"}
        - {name: "path", position: ".*"}
    labelColor:
      dataRef: "up"
      thresholds:
        - {color: "green", level: 1}
        - {color: "red",   level: 0}
      gradientMode: "none"

