---

cellIdPreamble: "cell-"

cells:
  user_throttle_inflow:
    dataRef: "up"
    label:
      separator: "replace"
      units: "ops"
    labelColor:
      thresholds:
        - {color: "green", level: 1}
        - {color: "red", level: 0}
