cellIdPreamble: ""
gradientMode: "hue"
datapoint: "last"

cells:
  "localhost:9100":
    dataRef: "up"

    label:
      dataRef: "up"
      text: "${instance}"
      decimalPoints: 0
      units: "none"
      separator: "cr"
      labelColor:
        dataRef: "up"
        thresholds:
          - {color: "green", level: 1}
          - {color: "red",   level: 0}
        gradientMode: "none"
        elementFilter:
          - {name: "text", position: ".*"}
        filterLabels:
          instance: "localhost:9100"   # Filtra solo esta instancia

    fillColor:
      dataRef: "up"
      thresholds:
        - {color: "green", level: 1}
        - {color: "red",   level: 0}
      gradientMode: "none"
      elementFilter:
        - {name: "path", position: ".*"}
        - {name: "rect", position: ".*"}
      filterLabels:
        instance: "localhost:9100"

    strokeColor:
      dataRef: "up"
      thresholds:
        - {color: "green", level: 1}
        - {color: "red",   level: 0}
      gradientMode: "none"
      elementFilter:
        - {name: "path", position: ".*"}
        - {name: "rect", position: ".*"}
      filterLabels:
        instance: "localhost:9100"
