---
cellIdPreamble: ""
gradientMode: "none"
datapoint: "last"

cells:
  node_exporter:
    dataRef: "node_exporter"
    fillColor:
      dataRef: "node_exporter"
      thresholds:
        - { color: "red",   level: 0 }
        - { color: "green",   level: 1 } 
      gradientMode: "none"
      elementFilter:
        - { name: "path", position: ".*" }  # aplicará a todos los path dentro del g
    label:
      separator: "replace"
