cellIdPreamble: 
gradientMode: "hue"

cells:
  "localhost:9100":   # El asterisco indica “todas las celdas”
    dataRef: 'up'
    labelColor:
      thresholds:
        - {color: "green", level: 1}
        - {color: "red", level: 0}
