cellIdPreamble: ""
gradientMode: "hue"
datapoint: "last"

cells:
  "localhost:9100":
    dataRef: "up"
    
    # Texto dentro del <text>
    label:
      dataRef: "up"
      text: "${instance}"
      decimalPoints: 0
      units: "none"
      separator: "cr"
      # Color del texto según el valor
      labelColor:
        dataRef: "up"
        thresholds:
          - {color: "green", level: 1}
          - {color: "red",   level: 0}
        gradientMode: "none"
        elementFilter:
          - {name: "text", position: ".*"}  # Aplica a tu <text> dentro del switch

    # Color de relleno de path/rect
    fillColor:
      dataRef: "up"
      thresholds:
        - {color: "green", level: 1}
        - {color: "red",   level: 0}
      gradientMode: "none"
      elementFilter:
        - {name: "path", position: ".*"}
        - {name: "rect", position: ".*"}

    # Color del borde de path/rect
    strokeColor:
      dataRef: "up"
      thresholds:
        - {color: "green", level: 1}
        - {color: "red",   level: 0}
      gradientMode: "none"
      elementFilter:
        - {name: "path", position: ".*"}
        - {name: "rect", position: ".*"}
