cellIdPreamble: ""
gradientMode: "hue"
datapoint: "last"

cells:
  "localhost:9100":
    dataRef: "up"
    label:
      dataRef: "up"
      text: "${instance}"
      decimalPoints: 0
      units: "none"
      separator: "cr"
      # Opcional: colores del texto si quieres que cambie
      labelColor:
        dataRef: "up"
        thresholds:
          - {color: "green", level: 1}
          - {color: "red",   level: 0}
        gradientMode: "none"

    fillColor:
      dataRef: "up"
      thresholds:
        - {color: "green", level: 1}
        - {color: "red",   level: 0}
      gradientMode: "none"
      elementFilter:
        - {name: "rect", position: ".*"}
        - {name: "path", position: ".*"}

    strokeColor:
      dataRef: "up"
      thresholds:
        - {color: "green", level: 1}
        - {color: "red",   level: 0}
      gradientMode: "none"
      elementFilter:
        - {name: "rect", position: ".*"}
        - {name: "path", position: ".*"}

