cellIdPreamble: 
gradientMode: "hue"

cells:
  "*":   # El asterisco indica “todas las celdas”
    dataRef: 'up{instance=~"$CELLID.*"}'
    labelColor:
      thresholds:
        - {color: "green", level: 1}
        - {color: "red", level: 0}
