---
cellIdPreamble: ""
datapoint: "last"

cells:
  node_exporter:
    dataRef: "node_exporter"

    fillColor:
      dataRef: "node_exporter"
      thresholds:
        - { color: "none", level: 1 }       # activo → conserva color original
        - { color: "#b5b5b5", level: 0 }    # caído → gris
      gradientMode: "none"
      elementFilter:
        - { name: "path", position: ".*", filter: 'fill!="#none"' }  # excluye fill="none"
        - { name: "path", position: ".*", filter: 'fill!="#fff"' }   # ignora los blancos

    strokeColor:
      dataRef: "node_exporter"
      thresholds:
        - { color: "green", level: 1 }      # borde verde si activo
        - { color: "red", level: 0 }        # borde rojo si caído
      gradientMode: "none"
      elementFilter:
        - { name: "path", position: ".*", filter: 'stroke="#b09500"' }

    label:
      separator: "replace"
