---
cells:
  "{{instance}}":
    dataRef: "{{instance}}"
    fillColor:
      dataRef: "{{instance}}"
      thresholds:
        - { color: "green", level: 1 }
        - { color: "red",   level: 0 }
      gradientMode: "none"
      elementFilter:
        - { name: "rect", position: ".*" }
        - { name: "path", position: ".*" }
    label:
      separator: "replace"
