cellIdPreamble: ""
gradientMode: "hue"
datapoint: "last"

cells:
  "localhost:9100":
    dataRef: "up"
    fillColor:
      dataRef: "up"
      thresholds:
        - {color: "green", level: 1}
        - {color: "red",   level: 0}
      gradientMode: "none"
      elementFilter:
        - {name: "rect", position: ".*"}

