---
cellIdPreamble: "cell-"
gradientMode: "none"
datapoint: "last"

cells:
  localhost_9100:
    dataRef: "up_localhost_9100"
    fillColor:
      dataRef: "up_localhost_9100"
      thresholds:
        # El orden importa: primero los niveles más bajos, luego los más altos
        - { color: "red",   level: 1 }      # <0.5 será rojo
        - { color: "green", level: 0 }    # ≥0.5 será verde
      gradientMode: "none"
      elementFilter:
        - { name: "rect", position: ".*" }
        - { name: "path", position: ".*" }
    label:
      separator: "replace"


